// metro.config.js
const { getDefaultConfig } = require('expo/metro-config');
const path = require('path');
const fs = require('fs');

const config = getDefaultConfig(__dirname);

const shimDir = path.resolve(__dirname, 'shims');
if (!fs.existsSync(shimDir)) fs.mkdirSync(shimDir, { recursive: true });

// ─── Shim 1: expo-web-browser ────────────────────────────────────────────────
let realWebBrowserEntry;
try { realWebBrowserEntry = require.resolve('expo-web-browser'); } catch (_) {}

const shimPath = path.resolve(shimDir, 'expo-web-browser-resolved.js');
if (realWebBrowserEntry) {
  fs.writeFileSync(shimPath, [
    '// Auto-generated by metro.config.js — do not edit.',
    `const real = require(${JSON.stringify(realWebBrowserEntry)});`,
    "if (typeof real.maybeCompleteAuthSession !== 'function') {",
    "  real.maybeCompleteAuthSession = function() { return { type: 'success' }; };",
    '}',
    'module.exports = real;',
  ].join('\n'), 'utf8');
} else {
  fs.writeFileSync(shimPath, [
    '// Fallback shim — expo-web-browser not found.',
    'module.exports = {',
    "  maybeCompleteAuthSession: function() { return { type: 'success' }; },",
    "  openAuthSessionAsync: async function() { return { type: 'cancel' }; },",
    "  openBrowserAsync: async function() { return { type: 'cancel' }; },",
    '  dismissBrowser: function() {},',
    '  dismissAuthSession: function() {},',
    '  warmUpAsync: async function() {},',
    '  coolDownAsync: async function() {},',
    '};',
  ].join('\n'), 'utf8');
}

// ─── Shim 2: VirtualView — react-native 0.85+ uses `match` syntax ───────────
// hermes-parser@0.25.1 cannot parse the `match (x) { ... }` proposal syntax.
// We replace VirtualView with a plain View passthrough so bundling succeeds.
const virtualViewStubPath = path.resolve(shimDir, 'VirtualView-stub.js');
fs.writeFileSync(virtualViewStubPath, [
  '// Auto-generated stub — VirtualView.js uses unsupported `match` syntax.',
  "'use strict';",
  "var React = require('react');",
  "var _View = require('react-native/Libraries/Components/View/View');",
  "var View = _View.default || _View.View || _View;",
  'function VirtualView(props) { return React.createElement(View, props); }',
  'VirtualView.displayName = "VirtualView";',
  'module.exports = VirtualView;',
  'module.exports.default = VirtualView;',
  'module.exports.VirtualView = VirtualView;',
].join('\n'), 'utf8');

// ─── Shim 3: react-native-gesture-handler (web / SSR) ───────────────────────
// On web, the real gesture-handler loads native modules that don't exist in
// the Node.js SSR environment used by expo-router's static renderer.
// We substitute a safe no-op shim so that top-level imports and component
// renders don't crash with "Cannot read properties of null" errors.
const gestureHandlerShimPath = path.resolve(shimDir, 'react-native-gesture-handler.js');

// ─── Shim 4: expo-constants (web / SSR) ────────────────────────────────────
// expo-router's router-store.js statically imports expo-constants, which tries
// to call requireOptionalNativeModule() — a native-only API that doesn't exist
// in the Node.js SSR environment. We replace it with a safe no-op shim.
const expoConstantsShimPath = path.resolve(shimDir, 'expo-constants.js');
fs.writeFileSync(expoConstantsShimPath, [
  '// Auto-generated shim — expo-constants is not available during web SSR.',
  "'use strict';",
  'module.exports = {',
  '  default: { manifest: {}, appOwnership: null, executionEnvironment: "storeClient", sessionId: "", statusBarHeight: 0, systemFonts: [], isHeadless: false },',
  '  ExecutionEnvironment: { Bare: "bare", Standalone: "storeClient", StoreClient: "storeClient" },',
  '};',
].join('\n'), 'utf8');

// ─── Shim 5: eslint-plugin-* and @typescript-eslint/* (web / SSR) ────────────
// eslint.config.js lives in the project root and Metro accidentally bundles it
// during SSR. These ESLint packages are Node-only and must never enter the
// browser/SSR bundle.
const nodeOnlyEmptyShimPath = path.resolve(shimDir, 'node-only-empty.js');
fs.writeFileSync(nodeOnlyEmptyShimPath, [
  '// Auto-generated empty shim for Node-only packages.',
  "'use strict';",
  'module.exports = {};',
].join('\n'), 'utf8');

// ─── Unified resolver ────────────────────────────────────────────────────────
const originalResolveRequest = config.resolver.resolveRequest;
config.resolver.resolveRequest = (context, moduleName, platform) => {
  // Intercept expo-web-browser
  if (moduleName === 'expo-web-browser') {
    return { filePath: shimPath, type: 'sourceFile' };
  }
  // Intercept VirtualView to avoid `match` parse error
  if (
    moduleName.includes('VirtualView') ||
    (moduleName.includes('virtualview'))
  ) {
    return { filePath: virtualViewStubPath, type: 'sourceFile' };
  }
  // Intercept react-native-gesture-handler on web/SSR to prevent native-module crash
  if (
    moduleName === 'react-native-gesture-handler' &&
    (platform === 'web' || platform == null)
  ) {
    return { filePath: gestureHandlerShimPath, type: 'sourceFile' };
  }
  // Intercept expo-constants on web/SSR to prevent requireOptionalNativeModule crash
  if (
    moduleName === 'expo-constants' &&
    (platform === 'web' || platform == null)
  ) {
    return { filePath: expoConstantsShimPath, type: 'sourceFile' };
  }
  // Intercept ESLint/TypeScript tooling packages that are Node-only —
  // Metro accidentally bundles eslint.config.js during SSR and these crash.
  const nodeOnlyPkgs = [
    'eslint-plugin-react',
    'eslint-plugin-react-hooks',
    '@typescript-eslint/parser',
    '@typescript-eslint/eslint-plugin',
    'eslint',
  ];
  if (
    nodeOnlyPkgs.some(pkg => moduleName === pkg || moduleName.startsWith(pkg + '/')) &&
    (platform === 'web' || platform == null)
  ) {
    return { filePath: nodeOnlyEmptyShimPath, type: 'sourceFile' };
  }
  if (originalResolveRequest) {
    return originalResolveRequest(context, moduleName, platform);
  }
  return context.resolveRequest(context, moduleName, platform);
};

module.exports = config;
